### PR TITLE
Part of sending messages

### PR DESCRIPTION
**Pull request by HuitingFENG**

### CODE REVIEW

**Comment by HuitingFENG** [comment]
add

**Comment by HuitingFENG** [comment]
add

**Comment by HuitingFENG** [comment]
I have added something to this projet for our last upload (problem: we still cannot store the input messages from user and display the chat box including those messages at the same time, which means that we can only store the messages in database with the previous version and we can only display the chatbox with the last final version), but I'm not sure if you can see it, maybe you can search my public repository in my account, many thanks!

**Comment by Paul-Benier** [comment]
Let's talk about it on Discord !

**Pull request closed without merging**
